// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH8VMNAqldVp-ENjMXrOWeFbHrMg--C3o',
    appId: '1:61238946419:web:8cee37b7cf9e39950cd806',
    messagingSenderId: '61238946419',
    projectId: 'lastbite-426fd',
    authDomain: 'lastbite-426fd.firebaseapp.com',
    storageBucket: 'lastbite-426fd.firebasestorage.app',
    measurementId: 'G-DLCW8RGG4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdDy99DnkrpFnWxEmKV07jc72VwcQI7kY',
    appId: '1:61238946419:android:56a7bc82c71d39fc0cd806',
    messagingSenderId: '61238946419',
    projectId: 'lastbite-426fd',
    storageBucket: 'lastbite-426fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsKyAzW3eWWTOYSUnh35m_LQNWA8kUHGM',
    appId: '1:61238946419:ios:38c2bb7ccd7c933c0cd806',
    messagingSenderId: '61238946419',
    projectId: 'lastbite-426fd',
    storageBucket: 'lastbite-426fd.firebasestorage.app',
    iosBundleId: 'com.example.lastbite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsKyAzW3eWWTOYSUnh35m_LQNWA8kUHGM',
    appId: '1:61238946419:ios:38c2bb7ccd7c933c0cd806',
    messagingSenderId: '61238946419',
    projectId: 'lastbite-426fd',
    storageBucket: 'lastbite-426fd.firebasestorage.app',
    iosBundleId: 'com.example.lastbite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH8VMNAqldVp-ENjMXrOWeFbHrMg--C3o',
    appId: '1:61238946419:web:b3625b013edab44b0cd806',
    messagingSenderId: '61238946419',
    projectId: 'lastbite-426fd',
    authDomain: 'lastbite-426fd.firebaseapp.com',
    storageBucket: 'lastbite-426fd.firebasestorage.app',
    measurementId: 'G-K978EECC9J',
  );
}
